const nodemailer = require('nodemailer');

let transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'omprajapatimca2@gmail.com',      // your Gmail
    pass: 'zwdq elww ssfy zmvq'          // Google App Password
  }
});

let mailOptions = {
  from: 'omprajapatimca2@gmail.com',
  to: 'omprajapatimca2@gmail.com',     // recipient who will receive the report
  subject: 'Playwright Test Report',
  text: 'Please find the attached Playwright test report.',
  attachments: [
    {
      filename: 'report.html',
      path: './playwright-report/index.html'  // path to the report generated by Playwright
    }
  ]
};

transporter.sendMail(mailOptions, function(error, info){
  if(error){
    console.log('Error sending email:', error);
  } else {
    console.log('Email sent successfully:', info.response);
  }
});