name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Print UTC and IST time
        run: |
          echo "UTC Time: $(date -u)"
          echo "IST Time: $(date -u -d '+5 hours 30 minutes')"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Tests
        run: npx playwright test

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report